### ISSUE TITLE
First pass at %near-handler gall agent

### ISSUE THREAD

**Issue by humanizersequel** [urbit/NEAR#2]
Gall agent that interfaces with our fork of the Near Social VM. The initial target is supporting methods that add and remove a list of accounts 

**EDIT - Updated Issue:**

%near-handler implements a `%poke` action that the frontend can poke to forward a poke to another agent.

`[%poke agent=@tas mark=@tas data=???]`

The hard part here is getting the type conversions right. What is the best way of converting the incoming frontend JSON to the action type for the receiving agent?

Demo: an Urbit app that, upon opening, simply displays a blank page and prints a message in dojo (or adds a pal, or something else trivial) via %near-handler.

**Comment by liam-fitzgerald** [comment]
Specification for gall agent
```hoon
+$  acc  @uxH
+$  action
  $%  [%add =acc]
          [%del =acc]
  ==
::  on-peek -> /x/accs  -> (set acc)
::  should %give %fact of %action as well
```

**Comment by hanfel-dovned** [comment]
- [ ] [Backstep notation](https://developers.urbit.org/reference/hoon/style#tall-layout-conventions)
- [ ] on-watch arm
- [ ] [nested core pattern](https://www.youtube.com/watch?v=eRz3s9dQZe8)
